### ISSUE TITLE
How to set the size of a QR code generated by the bb-qr-code plugin

### ISSUE THREAD

**Issue by ecxs** [rosnerdev/bb-qr-code#1]
Hi there,

Does anybody know how to set the size of a QR code that is generated with the help of the bb-qr-code plugin?

Thanks in advance!

https://github.com/Budibase/budibase/discussions/8768

**Comment by rosnerdev** [comment]
Hi!
Unfortunately, currently there is no way of doing that...
I'm kinda busy right now, but I will try to implement it as fast as I can.

**Comment by ecxs** [comment]
Hi @rosnerdev thanks for taking the time to implement this, and please keep met posted. Best regards, Dick

**Comment by kzkondo** [comment]
Hi. Thanks for the very good plugin. I would also like to have the ability to resize. Can you handle barcodes?

**Comment by rosnerdev** [comment]
> Hi. Thanks for the very good plugin. I would also like to have the ability to resize. Can you handle barcodes?

Hi! I'm not sure what you meant by "Can you handle barcodes?".

**Comment by rosnerdev** [comment]
> Hi. Thanks for the very good plugin. I would also like to have the ability to resize. Can you handle barcodes?

Hey, thanks for the request. I will start working on that once I finish with the QR code suggestion, which I haven't started yet.

**Comment by kzkondo** [comment]
Hi @rosnerdev Thank you very much. I'm looking forward to it.

**Comment by ecxs** [comment]
Him @rosnerdev thanks very much! It works, although it does not resize properly in Design mode.

**Comment by rosnerdev** [comment]
> Him @rosnerdev thanks very much! It works, although it does not resize properly in Design mode.

I will work on that, but it will take time.
