### ISSUE TITLE
I've updated it, but I can't resize it.

### ISSUE THREAD

**Issue by kzkondo** [rosnerdev/bb-qr-code#3]
Hi! @rosnerdev Thanks for the quick update.
I tried updating, but I can't change the size.

![スクリーンショット 2022-12-05 18 18 40](https://user-images.githubusercontent.com/93172658/205600593-edc8bff2-ae4c-445b-a9b5-6eff85a2e3fb.png)

![スクリーンショット 2022-12-05 18 18 58](https://user-images.githubusercontent.com/93172658/205600626-ffa1f059-e760-4bb0-a061-d5e5102c5106.png)

It doesn't change when you preview or publish. Anything else to try?

**Comment by rosnerdev** [comment]
> Hi! @rosnerdev Thanks for the quick update.
> I tried updating, but I can't change the size.
> 
> ![スクリーンショット 2022-12-05 18 18 40](https://user-images.githubusercontent.com/93172658/205600593-edc8bff2-ae4c-445b-a9b5-6eff85a2e3fb.png)
> 
> ![スクリーンショット 2022-12-05 18 18 58](https://user-images.githubusercontent.com/93172658/205600626-ffa1f059-e760-4bb0-a061-d5e5102c5106.png)
> スクリーンショット, I'm not sure how to fix this and this project isn't that active since I'm under high pressure in school.
> It doesn't change when you preview or publish. Anything else to try?

**Comment by rosnerdev** [comment]
Hi, It's probably an error on your side, for me it definitely works.

> Hi! @rosnerdev Thanks for the quick update. I tried updating, but I can't change the size.
> 
> ![スクリーンショット 2022-12-05 18 18 40](https://user-images.githubusercontent.com/93172658/205600593-edc8bff2-ae4c-445b-a9b5-6eff85a2e3fb.png)
> 
> ![スクリーンショット 2022-12-05 18 18 58](https://user-images.githubusercontent.com/93172658/205600626-ffa1f059-e760-4bb0-a061-d5e5102c5106.png)
> 
> It doesn't change when you preview or publish. Anything else to try?

Hi, It's probably an error on your side, for me it definitely works.
